## Single Server Queue Simulation

linux commit

### Import library

In [1]:
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

### Initialization the functions

In [46]:
class queueSim:
    def __init__(self, next_time, serv_time, total_cust):
        self.next_time = next_time
        self.serv_time = serv_time
        self.tot_cust = total_cust
        self.arr_time = np.zeros(total_cust, dtype=int)
        self.start_serv = np.zeros(total_cust, dtype=int)
        self.end_serv = np.zeros(total_cust, dtype=int)
        
    def simulation(self):
        

        for i in range(self.tot_cust):
            #arriveList[i] = dt.datetime.fromtimestamp(time).strftime('%H:%M')

            self.arr_time[i] = self.arr_time[i - 1] + self.next_time[i]
            self.start_serv[i] = max(self.arr_time[i], self.end_serv[i - 1])
            self.end_serv[i] = self.start_serv[i] + self.serv_time[i]

### Simulation

In [47]:
target_cust = 25
next_arr_time = np.random.normal(25, 3, target_cust).astype(int) * 60
service_time = np.random.normal(23, 5, target_cust).astype(int) * 60

queue1 = queueSim(next_arr_time, service_time, target_cust)
queue1.simulation()

In [64]:
df = pd.DataFrame([queue1.next_time, queue1.arr_time, queue1.serv_time, queue1.start_serv, queue1.end_serv]).T

In [65]:
df.columns = ['Next', 'Arrival', 'Service', 'Start', 'End']
df

Next  Arrival  Service  Start    End
0   1860     1860     1680   1860   3540
1   1800     3660     1440   3660   5100
2   1440     5100     1320   5100   6420
3   1500     6600     1020   6600   7620
4   1380     7980     1380   7980   9360
5   1380     9360     1020   9360  10380
6   1560    10920     1320  10920  12240
7   1440    12360     1200  12360  13560
8   1620    13980     1500  13980  15480
9   1740    15720     1620  15720  17340
10  1320    17040     1080  17340  18420
11  1260    18300     1260  18420  19680
12  1500    19800     1020  19800  20820
13  1680    21480     1200  21480  22680
14  1620    23100     2220  23100  25320
15  1680    24780     1560  25320  26880
16  1740    26520     1140  26880  28020
17  1440    27960     1260  28020  29280
18  1860    29820      780  29820  30600
19  1740    31560     1260  31560  32820
20  1920    33480     1500  33480  34980
21  1200    34680     1800  34980  36780
22  1440    36120     1260  36780  38040
23  1260    37380     1500  38040  39540
24  1380    38760     1560  39540  41100

In [48]:
queue1.arr_time

array([ 1860,  3660,  5100,  6600,  7980,  9360, 10920, 12360, 13980,
       15720, 17040, 18300, 19800, 21480, 23100, 24780, 26520, 27960,
       29820, 31560, 33480, 34680, 36120, 37380, 38760])

In [51]:
queue1.serv_time

array([1680, 1440, 1320, 1020, 1380, 1020, 1320, 1200, 1500, 1620, 1080,
       1260, 1020, 1200, 2220, 1560, 1140, 1260,  780, 1260, 1500, 1800,
       1260, 1500, 1560])

In [50]:
queue1.end_serv

array([ 3540,  5100,  6420,  7620,  9360, 10380, 12240, 13560, 15480,
       17340, 18420, 19680, 20820, 22680, 25320, 26880, 28020, 29280,
       30600, 32820, 34980, 36780, 38040, 39540, 41100])

In [49]:
queue1.start_serv

array([ 1860,  3660,  5100,  6600,  7980,  9360, 10920, 12360, 13980,
       15720, 17340, 18420, 19800, 21480, 23100, 25320, 26880, 28020,
       29820, 31560, 33480, 34980, 36780, 38040, 39540])